### PR TITLE
Improve grid placement

### LINKED ISSUE #48: Simple link event loop patterns are not well placed
### Describe the Bug

Here are two rather simple examples of using link events for a loop pattern. The top part is the original version (by me), the bottom part it the layouted version. As seen in my version, the elements would fit well on a grid.

Example 1:
image

Example 2:
image

### Steps to Reproduce

Run the layouter with the examples above.

### Expected Behavior

I expect the layouter to roughly follow my original version. The "happy path" should not diverge:
The merging gateway should be added to the first row and not behind the link catch event.
image

In a post-processing step, the link catch event could be moved two grid spaces to the right.

### Environment

- Host: React App (node 20.13.1) in Chrome browser
- OS: Windows 11
- Library version: 0.5.0

### PR DESCRIPTION
**Pull request by abdul99ahad**
Closes #48 , #49 , #50 
### Proposed Changes

 - Handled future incoming: Elements can only be visited until all the incoming elements have been visited. If some element has incoming from future, do nothing and wait for element to reappear in future. 
 - When multiple incoming/outgoing to an element, adjust its position in the grid. Handled in `incomingHandler` and `outgoingHandler`
 - Stack can now hold elements sort by type, e.g, if there are two elements, Task and ExclusiveGateway. First we'll configure Task and then gateways.
 - Added integration test cases
 

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by nikku** [comment]
I like the (simplified) algorithm you're proposing. How does it work against real world test cases?

> Handled future incoming: Elements can only be visited until all the incoming elements have been visited. 

How does this deal with loops?

**Comment by abdul99ahad** [comment]
> I like the (simplified) algorithm you're proposing. How does it work against real world test cases?
> 
> > Handled future incoming: Elements can only be visited until all the incoming elements have been visited.
> 
> How does this deal with loops?

Currently working on this resolution. This is the case which is not catered by this solution. 

image

**Comment by philippfromme** [comment]
I looked at this test case

image

and it seems to only work if there is at least one element between the gateways. Are we aware of this limitation?

brave_MQtR0kqH2u

**Comment by nikku** [comment]
I executed some additional testing, here some things I discovered:

### Disconnected Elements (edge case?)

Fails to layout (remaining elements not placed): 

image

### Loop without element in middle

Fails to layout:

image

Works: Layouts with more than one element in the loop (forward modeling):

image

Works: Properly "models forward only":

screenshot NXQKYG


----

Feature request for demo: Be able to download the currently modeled process.

**Comment by philippfromme** [comment]
Interestingly, if you remove the loop, all elements are present.

brave_iySirigjhb

**Comment by philippfromme** [comment]
> Feature request for demo: Be able to download the currently modeled process.

Here you go: https://github.com/bpmn-io/bpmn-auto-layout/pull/61

**Comment by abdul99ahad** [comment]
> I looked at this test case
> 
> image
> 
> and it seems to only work if there is at least one element between the gateways. Are we aware of this limitation?
> 
> brave_MQtR0kqH2u [ brave_MQtR0kqH2u ](https://private-user-images.githubusercontent.com/7633572/368971439-8cc93938-459e-4162-967d-fca021f1a33c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzgzMzAsIm5iZiI6MTcyNzA3ODAzMCwicGF0aCI6Ii83NjMzNTcyLzM2ODk3MTQzOS04Y2M5MzkzOC00NTllLTQxNjItOTY3ZC1mY2EwMjFmMWEzM2MuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjNUMDc1MzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTU5NTdlODdmYjMxZTEzNDNiM2NmMWZiMjY4YjViOWQzZTFhYzFiMjYzNmZhOTM1ZDFjNGMwNmQyMTJmOWM2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.jpXw-6aHmkNRCJlMgiCn6eu_BbfsN8pYv2zOTBxWhso) [ ](https://private-user-images.githubusercontent.com/7633572/368971439-8cc93938-459e-4162-967d-fca021f1a33c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzgzMzAsIm5iZiI6MTcyNzA3ODAzMCwicGF0aCI6Ii83NjMzNTcyLzM2ODk3MTQzOS04Y2M5MzkzOC00NTllLTQxNjItOTY3ZC1mY2EwMjFmMWEzM2MuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjNUMDc1MzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTU5NTdlODdmYjMxZTEzNDNiM2NmMWZiMjY4YjViOWQzZTFhYzFiMjYzNmZhOTM1ZDFjNGMwNmQyMTJmOWM2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.jpXw-6aHmkNRCJlMgiCn6eu_BbfsN8pYv2zOTBxWhso)

Created issue https://github.com/bpmn-io/bpmn-auto-layout/issues/62

**Comment by abdul99ahad** [comment]
> Interestingly, if you remove the loop, all elements are present.
> 
> brave_iySirigjhb 

This is because the deadlock occurs when the first element is both the only element in the stack and the looping element, causing it to return with no other elements left in the stack. 

Created issue: https://github.com/bpmn-io/bpmn-auto-layout/issues/64

**Comment by abdul99ahad** [comment]
> I executed some additional testing, here some things I discovered:
> 
> ### Disconnected Elements (edge case?)
> Fails to layout (remaining elements not placed):
> 
> image

Created issue: https://github.com/bpmn-io/bpmn-auto-layout/issues/63

**Comment by abdul99ahad** [comment]
> Works: Properly "models forward only":
> 
> screenshot NXQKYG
> 
@nikku needs clarity. Is the modeling correct or it should exactly depict the left one?

**Comment by nikku** [comment]
> https://github.com/bpmn-io/bpmn-auto-layout/pull/59#issuecomment-2367648592

This works correctly, as stated. We want to "model forward only".

**Comment by abdul99ahad** [comment]
> Sorting the elements to postpone laying out the gateways works in some cases but here's another case where it leads to new unexpected behavior:
> 
> image
> 
> The gateway is postponed so it's laid out only once all elements on the bottom have been laid out.
> 
> Even worse in this case (but was also bad before):
> 
> image

I've verified it, we need to adapt to some different strategy. Opened a [issue](https://github.com/bpmn-io/bpmn-auto-layout/issues/67).

**Comment by philippfromme** [comment]
Closed via https://github.com/bpmn-io/bpmn-auto-layout/commit/0a3bf8cd414ae2bedf3734203e10f18bd35fba43.

**Pull request closed without merging**
