### PR TITLE
fix: extra spaces after element

### LINKED ISSUE #47: Empty grid point behind task with boundary event
### Describe the Bug

When running the layouter, there is an unnecessary empty grid point behind a task with a boundary event:
image

This empty grid point helps with the layout when there is a gateway behind the task, but only if there are not too many elements following the boundary event. So this "help" is rather limited. On the other side, this empty grid point makes the process longer than necessary and creates a lot of "empty space".

### Steps to Reproduce

Layout a process with a task with a boundary event.

### Expected Behavior

I expect there to be no empty grid point behind a task with a boundary event.

(In the best case, the layouter can understand how many element follow behind the boundary event, and react accordingly, either using such empty grid points, or shifting the elements behind the boundary event to lower grid points.)

### Environment

- Host: React App (npm 10.7.0) in Chrome browser
- OS: Windows 11
- Library version: 0.5.0

### PR DESCRIPTION
**Pull request by abdul99ahad**
Closes #47

### Proposed Changes
image

- [x] No extra spaces after element

 

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by nikku** [comment]
Let's ensure this fix is accompanied by a test case.

**Review by nikku — CHANGES_REQUESTED** [review]
Cf. https://github.com/bpmn-io/bpmn-auto-layout/pull/55#issuecomment-2340832901

**Comment by philippfromme** [comment]
What is the state of this PR @abdul99ahad? Is it ready for another review?

**Comment by abdul99ahad** [comment]
> What is the state of this PR @abdul99ahad? Is it ready for another review?

Not yet. Waiting for https://github.com/bpmn-io/bpmn-auto-layout/pull/59 approval.

**Comment by abdul99ahad** [comment]
> Does this PR really depend on #59? @abdul99ahad It looks like we could merge this independently.

I think it's a good idea to wait for the resolution of big PR and then merge this one to avoid any further layout issues this may cause.

**Comment by abdul99ahad** [comment]
Ready for review. No extra spaces after boundary event task. 

Before: 
image

After: 
image

**Review by nikku — APPROVED** [review]
Removing code, I love it :slightly_smiling_face:

**Pull request merged**
