### PR TITLE
64 disconnected elements

### LINKED ISSUE #64: Disconnected Elements placement
### Describe the Bug

Disconnected Elements (edge case?)

Fails to layout (remaining elements not placed): 

image

### Steps to Reproduce

1. Model this 

[Playground for test](https://philippfrom.me/bpmn-auto-layout-playground/)

### Expected Behavior

The model should render correctly. The deadlock occurs because the first element is both the only element in the stack and the looping element, causing it to return with no other elements left in the stack.

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

### PR DESCRIPTION
**Pull request by abdul99ahad**
Closes #64 

### Proposed Changes

 
Start event and disjoint loop can now co-exist.
image

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [x] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by nikku** [comment]
This seems to conflict with recent changes introduced via #68. Could you have a look @abdul99ahad?

**Comment by abdul99ahad** [comment]
> This seems to conflict with recent changes introduced via #68. Could you have a look @abdul99ahad?

Sure

**Comment by philippfromme** [comment]
@abdul99ahad Let's get this ready for a review. Rebase on main and consider adding new snapshot tests.

**Comment by nikku** [comment]
Test already there via https://github.com/bpmn-io/bpmn-auto-layout/issues/64#issuecomment-2374529474.

**Comment by abdul99ahad** [comment]
> @abdul99ahad Let's get this ready for a review. Rebase on main and consider adding new snapshot tests.

Ready for review now.

**Review by nikku — APPROVED** [review]
Works, i.e. renders things.

Still not pretty with boundary events, but I'd regard that as an edge case:

image

**Pull request merged**
